### ISSUE TITLE
I find about non-ASCII character bug 

### ISSUE THREAD

**Issue by HeMinzhang** [Azure-Samples/active-directory-b2c-dotnetcore-webapp#43]
I use branch 2.0,I use Chinese operating system environment and get a error.
this is error in OpenIdConnectOptionsSetup.cs Line 98
context.Response.Redirect("/Home/Error?message=" + context.Failure.Message);

this is error message:

> An unhandled exception occurred while processing the request.
> InvalidOperationException: Invalid non-ASCII or control character in header: 0x000D
> Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ThrowInvalidHeaderCharacter(char ch)

This is the error details:

> InvalidOperationException: Invalid non-ASCII or control character in header: 0x000D
> Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ThrowInvalidHeaderCharacter(char ch)
> Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ValidateHeaderCharacters(string headerCharacters)
> Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ValidateHeaderCharacters(StringValues headerValues)
> Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseHeaders.SetValueFast(string key, StringValues value)
> Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item(string key, StringValues value)
> Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse.Redirect(string location, bool permanent)
> Microsoft.AspNetCore.Http.HttpResponse.Redirect(string location)
> Zop.Web.AzureAdB2CAuthenticationBuilderExtensions+OpenIdConnectOptionsSetup.OnRemoteFailure(RemoteFailureContext context) in OpenIdConnectOptionsSetup.cs
> +
>                     context.Response.Redirect("/Home/Error?message=" + context.Failure.Message);
> Microsoft.AspNetCore.Authentication.RemoteAuthenticationEvents.RemoteFailure(RemoteFailureContext context)
> Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult()
> Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> Microsoft.AspNetCore.Session.SessionMiddleware+<Invoke>d__9.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> Microsoft.AspNetCore.Session.SessionMiddleware+<Invoke>d__9.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by parakhj** [comment]
Could you paste the failure message? context.Failure.Message

**Comment by HeMinzhang** [comment]
@parakhj 

failure.Message:	"AADB2C90081: The specified client_secret does not match the expected value for this client. Please correct the client_secret and try again.\r\nCorrelation ID: ac653eed-60ab-4d56-ad16-5dfde8a9bb8f\r\nTimestamp: 2018-01-28 04:56:16Z\r\n"	string
failure.ResponseBody:	"{\"error\":\"invalid_client\",\"error_description\":\"AADB2C90081: The specified client_secret does not match the expected value for this client. Please correct the client_secret and try again.\\r\\nCorrelation ID: ac653eed-60ab-4d56-ad16-5dfde8a9bb8f\\r\\nTimestamp: 2018-01-28 04:56:16Z\\r\\n\"}"	string

**Comment by HeMinzhang** [comment]
-		Failure	{Microsoft.Identity.Client.MsalServiceException: AADB2C90081: The specified client_secret does not match the expected value for this client. Please correct the client_secret and try again.
Correlation ID: ac653eed-60ab-4d56-ad16-5dfde8a9bb8f
Timestamp: 2018-01-28 04:56:16Z

   at Microsoft.Identity.Client.Internal.OAuth2.OAuth2Client.CreateErrorResponse(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.Internal.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext, Boolean addCorrelationId)
   at Microsoft.Identity.Client.Internal.OAuth2.OAuth2Client.<ExecuteRequest>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.OAuth2.OAuth2Client.<GetToken>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<SendHttpMessageAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<SendTokenRequestAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ConfidentialClientApplication.<AcquireTokenByAuthorizationCodeCommonAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ConfidentialClientApplication.<AcquireTokenByAuthorizationCodeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Zop.Web.AzureAdB2CAuthenticationBuilderExtensions.OpenIdConnectOptionsSetup.<OnAuthorizationCodeReceived>d__9.MoveNext() in D:\Programing\DevelopingSolution\ZopCommerce\Presentation\Zop.Web\OpenIdConnectOptionsSetup.cs:line 122
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<RunAuthorizationCodeReceivedEventAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleRemoteAuthenticateAsync>d__21.MoveNext()
	ErrorCode: invalid_client
	StatusCode: 400
	Claims: }	System.Exception {Microsoft.Identity.Client.MsalServiceException}

**Comment by parakhj** [comment]
Doesn't seem like any chinese characters are in the error message. Could you check the client secret if any characters were accidentally added?

**Comment by HeMinzhang** [comment]
@parakhj  Yes,I know settings is error.But it make a can't catch exception.
**Thanks a million.**

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived and replaced by a newer ASP.NET Core 3.1 sample.
See Readme.md
